import { INITIAL_TOKEN_BALANCE, GENERATE_COST, FREE_TIER_UPLOAD_LIMIT, DAILY_GENERATE_LIMIT } from "@/lib/token-constants";

export const FREE_TIER = {
  INITIAL_BALANCE: INITIAL_TOKEN_BALANCE,
  GENERATE_COST,
  FREE_GENERATIONS: Math.floor(INITIAL_TOKEN_BALANCE / GENERATE_COST),
  UPLOAD_LIMIT: FREE_TIER_UPLOAD_LIMIT,
  MAX_FILE_SIZE: 10 * 1024 * 1024,
  DAILY_GENERATE_LIMIT,
} as const;

export function getFreeTierSummary() {
  return {
    rupiah: FREE_TIER.INITIAL_BALANCE.toLocaleString("id-ID"),
    gratis: FREE_TIER.FREE_GENERATIONS,
    biayaPerGenerate: FREE_TIER.GENERATE_COST,
    uploadGratis: FREE_TIER.UPLOAD_LIMIT,
  };
}